package ph.edu.cksc.college.appdev.appdev2025

const val MAIN_SCREEN = "MainScreen"
const val ABOUT_SCREEN = "AboutScreen"
const val DIARY_ENTRY_SCREEN = "DiaryEntryScreen"
const val MAP_SCREEN = "MapScreen"
const val FAVORITE_FOOD_SCREEN = "FavoriteFoodScreen"
const val FOOD_SCREEN = "FoodScreen"
const val REGISTER_SCREEN = "RegisterScreen"
const val GALLERY_SCREEN = "GalleryScreen"
const val FAVORITE_SCREEN = "FavoriteScreen"
const val DEVELOPER_SCREEN = "DeveloperScreen"
const val AUTH_SCREEN = "AuthScreen"
const val SPLASH_SCREEN = "SplashScreen"
const val SETTINGS_SCREEN = "SettingsScreen"
const val LOGIN_SCREEN = "LoginScreen"
const val LOGINACTIVITY_SCREEN = "LoginActivityScreen"
const val CALCULATOR_SCREEN = "CalculatorScreen"
const val TASKMANAGER_SCREEN = "TaskManagerScreen"
const val STATS_SCREEN = "StatsScreen"
const val SIGN_UP_SCREEN = "SignUpScreen"
//const val TASKS_SCREEN = "TasksScreen"
//const val EDIT_TASK_SCREEN = "EditTaskScreen"

const val TASK_ID = "taskId"
const val TASK_ID_ARG = "?$TASK_ID={$TASK_ID}"